config/routes.rb
Dbc::Application.routes.draw do
  resources :cups

  match 'plots' => 'plots#index'
  match 'plots/collective' => 'plots#collective'
  match ':drank_by' => 'plots#user', :as => :user_plot

  root :to => "plots#collective"

end

app/models/cup.rb
class Cup < ActiveRecord::Base

  default_scope order('created_at')

  validates_presence_of :drank_by

  def as_json(params={})
    super(params.merge({:methods => :milliseconds}))
  end

  def milliseconds
    central_timezone_offset = 6 * 60 * 60
    (created_at.to_i - central_timezone_offset) * 1000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  # GET /cups
  # GET /cups.json
  def index
    if(params[:drank_by])
      @cups = Cup.where(:drank_by => params[:drank_by])
    else
      @cups = Cup.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @cups }
    end
  end

  # GET /cups/1
  # GET /cups/1.json
  def show
    @cup = Cup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @cup }
    end
  end

  # GET /cups/new
  # GET /cups/new.json
  def new
    @cup = Cup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @cup }
    end
  end

  # GET /cups/1/edit
  def edit
    @cup = Cup.find(params[:id])
  end

  # POST /cups
  # POST /cups.json
  def create
    @cup = Cup.new(params[:cup])

    respond_to do |format|
      if @cup.save
        format.html { redirect_to(user_plot_path(:drank_by=>@cup.drank_by), :notice => 'Cup was successfully created.') }
        format.json  { render :json => @cup, :status => :created, :location => @cup }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @cup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cups/1
  # PUT /cups/1.json
  def update
    @cup = Cup.find(params[:id])

    respond_to do |format|
      if @cup.update_attributes(params[:cup])
        format.html { redirect_to(@cup, :notice => 'Cup was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @cup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cups/1
  # DELETE /cups/1.json
  def destroy
    @cup = Cup.find(params[:id])
    @cup.destroy

    respond_to do |format|
      format.html { redirect_to(cups_url) }
      format.json  { head :ok }
    end
  end
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  def user
    @cups_url = "cups.json?drank_by=#{params[:drank_by]}"
    respond_to do |format|
      format.html
    end
  end

  def collective
    @cups_url = "cups.json"
    respond_to do |format|
      format.html
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cups_helper.rb
module CupsHelper
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/views/cups/_form.html.erb
<%= form_for(@cup) do |f| %>
  <% if @cup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cup.errors.count, "error") %> prohibited this cup from being saved:</h2>

      <ul>
      <% @cup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :drank_by %><br />
    <%= f.text_field :drank_by %> 
  </div>
  
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_field :memo %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cups/edit.html.erb
<h1>Editing cup</h1>

<%= render 'form' %>

<%= link_to 'Show', @cup %> |
<%= link_to 'Back', cups_path %>

app/views/cups/index.html.erb
<h1>Listing cups</h1>

<table>
  <tr>
    <th>Consumed</th>
    <th>Memo</th>
    <th>Drank by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cups.each do |cup| %>
  <tr>
    <td><%= cup.created_at %></td>
    <td><%= cup.memo %></td>
    <td><%= cup.drank_by %></td>
    <td><%= link_to 'Show', cup %></td>
    <td><%= link_to 'Edit', edit_cup_path(cup) %></td>
    <td><%= link_to 'Destroy', cup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cup', new_cup_path %>

app/views/cups/new.html.erb
<h1>New cup</h1>

<%= render 'form' %>

<%= link_to 'Back', cups_path %>

app/views/cups/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Cup <%= @cup.id %></h1>
<p>
Consumed <%= time_ago_in_words(@cup.created_at) %> ago by <%= @cup.drank_by %>.
</p>

<% if @cup.memo %>
<p><strong>memo:</strong>
<%= @cup.memo %>
</p>
<% end %>


<%= link_to 'Edit', edit_cup_path(@cup) %> |
<%= link_to 'Back', cups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Death by Coffee</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>
  <%= javascript_include_tag 'rails', 'application' %>
  <%= javascript_include_tag 'jquery.flot.js' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plots/_plot.html.erb
<div id="plot" style="width:100%;height:500px;clear: both;">
</div>

<div class="block-quote">
  <p class="source">
    From <a href="http://www.erowid.org/chemicals/caffeine/">the vaults of erowid</a>:
  </p>

<p>
Caffeine doses of 200 mg or higher can cause <strong>unpleasant symptoms</strong> including nausea, headache, and irregular heartbeat, while dose of 750 - 1000 mg can cause <strong>severe toxic symptoms</strong>. Severe caffeine intoxication can result in nausea, vomiting, anxiety, tremor, seizures, tachycardia, dysrhythmias, hypotension, hypokalemia, and metabolic acidosis.
</p>
<p>
Several fatalities resulting from caffeine overdose have been documented, but they are extremely rare relative to its widespread use. In the case of a massive caffeine overdose, vomiting often protects against fatal poisoning, but some deaths have still resulted. 
</p>
<p>
Fatal dose range in humans is believed to be between 3 - 20 grams, approximately the amount of caffeine found in 20 - 130 cups of drip coffee or 15-100 common caffeine tablets (200 mg each). Blood caffeine levels greater than 80 ug/mL have been associated with death, but data is limited. It is difficult to ingest such high levels of caffeine accidentally, and many of the documented fatalities appear to be suicide attempts involving the ingestion of a large number of caffeine pills.
</p>
</div>

<script language="javascript" type="text/javascript">
  function draw_caffeine_plot(cups){
    //points marking each coffee consumption
    var consumed = [];

    //time (milliseconds from epoch) indexed caffeine level
    var caffeine = [];

    //approx half life of caffeine
    var half_life = 18000000; 

    var now = Date.now() - 6 * 60 * 60 * 1000;

    //initialize caffeine level just before first cup
    var previous_level = 0;
    var caffeine_level = 0;
    var first_time = cups[0].milliseconds;
    var caffeine_dose = 150; //mg of caffeine in a cup of coffee

    // we will only display dose lines
    // if the caffeine level is relevantly high
    var display_fatal_dose = false;
    var display_severe_toxicity = false;

    for(i=0; i < cups.length; i++){
      var time = cups[i].milliseconds;
      var next_cup = cups[i+1];
      var next_time = null;

      if(next_cup == undefined){
        //if this is the last cup, extrapolote 20 hours into the future
        next_time = time + half_life * 4;
        var last_time = next_time;
      } else { //if there is a next cup extrapolote to it
        next_time = next_cup.milliseconds;
      }

      //bump caffeine level
      caffeine_level = caffeine_level + caffeine_dose;
      consumed.push([time, caffeine_level]);

      //toggle relevant lines
      if (caffeine_level > 500){
        display_severe_toxicity = true;
      }
      if (caffeine_level > 2500){
        display_fatal_dose = true;
      }


      // fill in caffeine level piecewise between events
      var range = next_time - time;
      var step_count = 30; //points calculated between events
      var step_size = range / step_count;
      if(step_size < (1000 * 60)){
        step_size = 60 * 1000 //a stepsize of at least 1 minute
      }
      //use previous level as base for piecewise function
      previous_level = caffeine_level;
      for(var t = time; t <= next_time; t = t + step_size){
        caffeine_level = previous_level * Math.pow(1/2, ((t - time) / half_life ));
        caffeine.push([t, caffeine_level]);
      }
    }
    var current_level = previous_level * Math.pow(1/2, ((now - time) / half_life ));

    var now_series = [[now, current_level]];

    var unpleasant_symptoms = [[first_time, 200], [last_time, 200]];
    debugger;
    var plots =[{data: consumed, 
                 points: {show: true, clickable: true},
                 lines: {show: false}},
               {label: "mg of caffeine in your body", data: caffeine},
               {label: "unpleasant symptoms", data: unpleasant_symptoms}];

    if(display_severe_toxicity){
      var severe_toxicity = [[first_time, 750], [last_time, 750]];
      plots.push({label: "severe toxicity", data: severe_toxicity})
    }
    if(display_fatal_dose){
      var fatal_dose = [[first_time, 3000], [last_time, 3000]];
      plots.push({label: "potentially fatal dose (be careful!)", data: fatal_dose})
    }
    if(now < last_time){ //won't display if we're viewing data too far in the past.
      plots.push({label: "right now", data: now_series, points: {show: true, radius: 5}})
    }

    $.plot($("#plot"), 
        plots, 
        {xaxis: {
          mode: "time", 
          label: "Time (UTC)",
          timeformat: "%y/%m/%d %h%P"},
         grid: {
          clickable: true},
         legend: {
          position: 'ne'}});
  }
  $.getJSON('<%= @cups_url %>', draw_caffeine_plot);
</script>

app/views/plots/collective.html.erb
<h1>Collective plot</h1>
<p>
A plot of our collective caffeine level.
</p>

<%= render :partial => 'plot' %>

app/views/plots/user.html.erb
<style type="text/css">
  form.button_to[action^="/cups"] {
    border: solid black 4px;
    height: 200px;
    width: 300px;
    float: right;
  }
  form.button_to[action^="/cups"] div{
    text-align: center;
  }

  form.button_to[action^="/cups"] input[type="submit"]{
    cursor: pointer;
    background-image: url('/images/300px-A_small_cup_of_coffee.JPG');
    height: 200px;
    width: 300px;
    border: none;
    color: #FFFF00;
    font-size: 30px;
    font-weight: 700;
    white-space: normal;
  }
</style>
<%= button_to("Drink another cup #{params[:drank_by]}!", { :action => 'create', :cup => {:drank_by => params[:drank_by]}, :controller => 'cups'}) %>

<h1><%= params[:drank_by] %>'s plot</h1>
<p>
A plot of <%= params[:drank_by] %>'s caffeine level.
</p>

<%= render :partial => 'plot' %>